title: "大好きな開発チームに捧ぐ、SDETからのテストの書き方の提案"
summary: "私は開発チームが大好きです。そんな皆さんの口から出てきた疑問などをまとめ、私の意見を述べさせていただきました。"
topics: ["test", "unittest"] # トピック（5つまで）
published: false # falseだと下書き
price: 0 # 有料の場合200〜5000
chapters:
  - readme # チャプター1
  # ここらへんに開発者テストって何？みたいなのを入れないといけないかも
  - test-title
